version: 2.1
jobs:
  build:
    docker:
    - image: circleci/php:7.3-node-browsers
    - image: circleci/node:14.0.0-browsers

    environment:
    - APP_ENV=local
    - APP_KEY=base64:fXVG/tgUvgPX1ml2ZwJXO7d+57MJqeEmHZZqZeIL+tQ=
    - APP_DEBUG=true
    - APP_URL=http://localhost:8080

    steps:
    - checkout
    - setup_remote_docker

    - run: sudo apt update
    - run: sudo docker-php-ext-install zip
    - run:
        name: php test
        command: vendor/bin/phpunit


